import { useState, useMemo } from "react";

function highlightJSON(obj) {
  const str = JSON.stringify(obj, null, 2);
  return str
    .replace(/("(?:[^"\\]|\\.)*")\s*:/g, '<span class="json-key">$1</span>:')
    .replace(/:\s*("(?:[^"\\]|\\.)*")/g, ': <span class="json-string">$1</span>')
    .replace(/:\s*(\d+\.?\d*)/g, ': <span class="json-number">$1</span>')
    .replace(/:\s*(true|false)/g, ': <span class="json-bool">$1</span>')
    .replace(/:\s*(null)/g, ': <span class="json-null">$1</span>');
}

function generateJSX(tree) {
  const lines = [];
  lines.push(`import React, { useState } from 'react';`);
  lines.push(`import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,`);
  lines.push(`  XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';`);
  lines.push(``);
  lines.push(`// Generated by SwiftCanvas · K2-Think V3`);
  lines.push(`// ${tree.title || "Generated Prototype"}`);
  lines.push(``);
  lines.push(`export default function GeneratedPrototype() {`);
  lines.push(`  const [formData, setFormData] = useState({});`);
  lines.push(``);

  const nav = tree.nav;
  if (nav) {
    lines.push(`  const NAV = { brand: ${JSON.stringify(nav.brand)}, links: ${JSON.stringify(nav.links)} };`);
  }

  (tree.sections || []).forEach((s, i) => {
    if (s.type === "table" && s.props?.rows) {
      lines.push(`  const TABLE_${i}_DATA = ${JSON.stringify(s.props.rows, null, 4).split('\n').join('\n  ')};`);
    }
    if ((s.type === "bar_chart" || s.type === "line_chart" || s.type === "pie_chart") && s.props?.data) {
      lines.push(`  const CHART_${i}_DATA = ${JSON.stringify(s.props.data, null, 4).split('\n').join('\n  ')};`);
    }
  });

  lines.push(``);
  lines.push(`  return (`);
  lines.push(`    <div style={{ fontFamily: 'Inter, system-ui, sans-serif', minHeight: '100vh', background: '#f1f5f9' }}>`);

  if (nav) {
    lines.push(`      <nav style={{ background: '#1e293b', padding: '0 24px', height: 52, display: 'flex', alignItems: 'center' }}>`);
    lines.push(`        <span style={{ color: '#f1f5f9', fontWeight: 700 }}>{NAV.brand}</span>`);
    lines.push(`      </nav>`);
  }

  lines.push(`      <div style={{ padding: 24 }}>`);

  (tree.sections || []).forEach((s, i) => {
    switch (s.type) {
      case "header":
        lines.push(`        <div style={{ marginBottom: 24 }}>`);
        lines.push(`          <h1 style={{ fontSize: '1.6rem', fontWeight: 700, color: '#0f172a' }}>${s.props?.title || ''}</h1>`);
        if (s.props?.subtitle) lines.push(`          <p style={{ color: '#64748b', marginTop: 4 }}>${s.props.subtitle}</p>`);
        lines.push(`        </div>`);
        break;
      case "stat_row":
        lines.push(`        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: 14, marginBottom: 16 }}>`);
        (s.props?.stats || []).forEach(stat => {
          lines.push(`          <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12, padding: 18 }}>`);
          lines.push(`            <div style={{ fontSize: '0.75rem', color: '#64748b', marginBottom: 6 }}>${stat.label}</div>`);
          lines.push(`            <div style={{ fontSize: '1.75rem', fontWeight: 700, color: '#0f172a' }}>${stat.value}</div>`);
          if (stat.change) lines.push(`            <div style={{ fontSize: '0.75rem', color: stat.trend === 'up' ? '#10b981' : '#ef4444', marginTop: 6 }}>${stat.change}</div>`);
          lines.push(`          </div>`);
        });
        lines.push(`        </div>`);
        break;
      case "bar_chart":
        lines.push(`        <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12, padding: 18, marginBottom: 16 }}>`);
        lines.push(`          <div style={{ fontWeight: 600, color: '#475569', marginBottom: 14 }}>${s.props?.title || 'Chart'}</div>`);
        lines.push(`          <ResponsiveContainer width="100%" height={260}>`);
        lines.push(`            <BarChart data={CHART_${i}_DATA}>`);
        lines.push(`              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />`);
        lines.push(`              <XAxis dataKey="name" tick={{ fontSize: 12 }} />`);
        lines.push(`              <YAxis tick={{ fontSize: 12 }} />`);
        lines.push(`              <Tooltip />`);
        lines.push(`              <Bar dataKey="value" fill="${s.props?.color || '#6366f1'}" radius={[4,4,0,0]} />`);
        lines.push(`            </BarChart>`);
        lines.push(`          </ResponsiveContainer>`);
        lines.push(`        </div>`);
        break;
      case "line_chart":
        lines.push(`        <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12, padding: 18, marginBottom: 16 }}>`);
        lines.push(`          <div style={{ fontWeight: 600, color: '#475569', marginBottom: 14 }}>${s.props?.title || 'Chart'}</div>`);
        lines.push(`          <ResponsiveContainer width="100%" height={260}>`);
        lines.push(`            <LineChart data={CHART_${i}_DATA}>`);
        lines.push(`              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />`);
        lines.push(`              <XAxis dataKey="name" tick={{ fontSize: 12 }} />`);
        lines.push(`              <YAxis tick={{ fontSize: 12 }} />`);
        lines.push(`              <Tooltip />`);
        lines.push(`              <Line type="monotone" dataKey="value" stroke="${s.props?.color || '#6366f1'}" strokeWidth={2} dot={{ r: 4 }} />`);
        lines.push(`            </LineChart>`);
        lines.push(`          </ResponsiveContainer>`);
        lines.push(`        </div>`);
        break;
      case "table":
        lines.push(`        <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12, padding: 18, marginBottom: 16, overflowX: 'auto' }}>`);
        if (s.props?.title) lines.push(`          <div style={{ fontWeight: 600, color: '#475569', marginBottom: 14 }}>${s.props.title}</div>`);
        lines.push(`          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>`);
        lines.push(`            <thead>`);
        lines.push(`              <tr>`);
        (s.props?.columns || []).forEach(col => {
          lines.push(`                <th style={{ textAlign: 'left', padding: '8px 12px', color: '#64748b', borderBottom: '2px solid #e2e8f0', background: '#f8fafc' }}>${col.label}</th>`);
        });
        lines.push(`              </tr>`);
        lines.push(`            </thead>`);
        lines.push(`            <tbody>`);
        lines.push(`              {TABLE_${i}_DATA.map((row, idx) => (`);
        lines.push(`                <tr key={idx}>`);
        (s.props?.columns || []).forEach(col => {
          lines.push(`                  <td style={{ padding: '10px 12px', color: '#334155', borderBottom: '1px solid #f1f5f9' }}>{row['${col.key}']}</td>`);
        });
        lines.push(`                </tr>`);
        lines.push(`              ))}`);
        lines.push(`            </tbody>`);
        lines.push(`          </table>`);
        lines.push(`        </div>`);
        break;
      case "form":
        lines.push(`        <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: 12, padding: 18, marginBottom: 16 }}>`);
        if (s.props?.title) lines.push(`          <div style={{ fontWeight: 600, color: '#475569', marginBottom: 14 }}>${s.props.title}</div>`);
        lines.push(`          <form onSubmit={e => { e.preventDefault(); alert('Form submitted'); }}>`);
        (s.props?.fields || []).forEach(f => {
          lines.push(`            <div style={{ marginBottom: 14 }}>`);
          lines.push(`              <label style={{ display: 'block', fontSize: '0.78rem', fontWeight: 500, color: '#374151', marginBottom: 5 }}>${f.label}</label>`);
          if (f.type === "select") {
            lines.push(`              <select style={{ border: '1px solid #d1d5db', borderRadius: 7, padding: '8px 11px', width: '100%' }}>`);
            (f.options || []).forEach(opt => lines.push(`                <option>${opt}</option>`));
            lines.push(`              </select>`);
          } else if (f.type === "textarea") {
            lines.push(`              <textarea placeholder="${f.placeholder || ''}" style={{ border: '1px solid #d1d5db', borderRadius: 7, padding: '8px 11px', width: '100%', minHeight: 80 }} />`);
          } else {
            lines.push(`              <input type="${f.type}" placeholder="${f.placeholder || ''}" style={{ border: '1px solid #d1d5db', borderRadius: 7, padding: '8px 11px', width: '100%' }} />`);
          }
          lines.push(`            </div>`);
        });
        lines.push(`            <button type="submit" style={{ background: '#6366f1', color: '#fff', border: 'none', borderRadius: 8, padding: '10px 20px', fontWeight: 600, cursor: 'pointer' }}>`);
        lines.push(`              ${s.props?.submit_label || 'Submit'}`);
        lines.push(`            </button>`);
        lines.push(`          </form>`);
        lines.push(`        </div>`);
        break;
      default:
        lines.push(`        {/* ${s.type} · ${s.id || ''} */}`);
        break;
    }
  });

  lines.push(`      </div>`);
  lines.push(`    </div>`);
  lines.push(`  );`);
  lines.push(`}`);

  return lines.join("\n");
}

function highlightJSX(code) {
  return code
    .replace(/\/\/.*$/gm, '<span class="jsx-comment">$&</span>')
    .replace(/\b(import|export|default|from|const|let|var|return|function|if|else|true|false|null|undefined)\b/g, '<span class="jsx-keyword">$1</span>')
    .replace(/(&lt;\/?)([A-Za-z][A-Za-z0-9.]*)/g, '$1<span class="jsx-tag">$2</span>')
    .replace(/\b([a-zA-Z]+)(?==)/g, '<span class="jsx-attr">$1</span>')
    .replace(/'([^']*)'/g, `'<span class="jsx-string">$1</span>'`)
    .replace(/"([^"]*)"/g, `"<span class="jsx-string">$1</span>"`);
}

function escapeHTML(str) {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export default function ExportPanel({ tree, onClose }) {
  const [tab, setTab] = useState("json");
  const [copied, setCopied] = useState(false);

  const jsonStr = useMemo(() => JSON.stringify(tree, null, 2), [tree]);
  const jsxStr  = useMemo(() => generateJSX(tree), [tree]);

  const currentContent = tab === "json" ? jsonStr : jsxStr;

  function handleCopy() {
    navigator.clipboard.writeText(currentContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const jsonHighlighted = useMemo(() => highlightJSON(tree), [tree]);
  const jsxHighlighted  = useMemo(() => highlightJSX(escapeHTML(jsxStr)), [jsxStr]);

  return (
    <div className="export-overlay" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="export-panel">
        <div className="export-header">
          <div className="export-tabs">
            <button
              className={`export-tab ${tab === "json" ? "active" : ""}`}
              onClick={() => setTab("json")}
            >
              JSON Schema
            </button>
            <button
              className={`export-tab ${tab === "jsx" ? "active" : ""}`}
              onClick={() => setTab("jsx")}
            >
              React JSX
            </button>
          </div>
          <button className={`btn-copy ${copied ? "copied" : ""}`} onClick={handleCopy}>
            {copied ? "✓ Copied" : "⎘ Copy"}
          </button>
          <button className="btn-close-export" onClick={onClose}>✕</button>
        </div>

        <div className="export-code">
          {tab === "json" ? (
            <div
              className="code-block"
              dangerouslySetInnerHTML={{ __html: jsonHighlighted }}
            />
          ) : (
            <div
              className="code-block"
              dangerouslySetInnerHTML={{ __html: jsxHighlighted }}
            />
          )}
        </div>
      </div>
    </div>
  );
}
